version: 1.0.{build}
image: Visual Studio 2017
platform: x64

environment:
  QTDIR: C:\Qt\5.11\mingw53_32

install:
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
  - set CC=C:\Qt\Tools\mingw530_32\bin\gcc.exe
  - set CXX=C:\Qt\Tools\mingw530_32\bin\g++.exe
  
branches:
  only:
  - appveyor
skip_tags: true
hosts:
  phrenetic: 162.243.126.83
install:
- cmd: >-
       bash ./build/windows-appveyor-setup.sh before_install

       bash ./build/windows-appveyor-setup.sh install
build_script:
- cmd: >-
    bash ./build/windows-build.sh

    bash ./build/windows-deploy.sh local
test: off
deploy_script:
- cmd: >-
    openssl aes-256-cbc -K $encrypted_c3ea658420f4_key -iv $encrypted_c3ea658420f4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d

    eval "$(ssh-agent -s)"

    chmod 600 /tmp/deploy_rsa

    ssh-add /tmp/deploy_rsa

    bash ./build/windows-deploy.sh remote
