os:
    - linux
    - osx

osx_image: xcode9.1

language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - travis_wait 40 ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - travis_wait 40 ./build/${TRAVIS_OS_NAME}-travis-setup.sh install

script:
  - cd build
  - travis_wait 40 ./build.sh 
  - travis_wait 40 ./${TRAVIS_OS_NAME}-deploy.sh
