os:
    - osx
    - linux

language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - travis_wait ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install

install:
  - travis_wait ./build/${TRAVIS_OS_NAME}-travis-setup.sh install

script:
  - cd build
  - travis_wait ./build.sh 
  - travis_wait ./${TRAVIS_OS_NAME}-deploy.sh
