os:
- linux
- osx
- windows
osx_image: xcode10.1
dist: xenial
language: cpp
before_install:
- echo $TRAVIS_OS_NAME
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then travis_wait 60 bash ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 60 ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then travis_wait 60 bash ./build/${TRAVIS_OS_NAME}-travis-setup.sh install; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 60 ./build/${TRAVIS_OS_NAME}-travis-setup.sh install; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then travis_wait 60 bash ./build/${TRAVIS_OS_NAME}-build.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then travis_wait 60 bash ./build/${TRAVIS_OS_NAME}-deploy.sh local; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 60 ./build/${TRAVIS_OS_NAME}-build.sh; fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_wait 60 ./build/${TRAVIS_OS_NAME}-deploy.sh local; fi
addons:
  ssh_known_hosts: 162.243.126.83
before_deploy: 
- openssl aes-256-cbc -K $encrypted_c3ea658420f4_key -iv $encrypted_c3ea658420f4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  overwrite: true
  script: bash ./build/${TRAVIS_OS_NAME}-deploy.sh remote
  on:
    branch: master
    repo: christopherpow/nesicide
notifications:
  irc:
    channels:
    - chat.freenode.net#nesicide
    template:
    - "%{repository_slug} (%{commit}) : %{message}"
    - 'Build details: %{build_url}'
