os:
    - osx
    - linux

osx_image: xcode9.1

language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - travis_wait 40 ./build/${TRAVIS_OS_NAME}-travis-setup.sh before_install

install:
  - travis_wait 40 ./build/${TRAVIS_OS_NAME}-travis-setup.sh install

script:
  - cd build
  - travis_wait 40 ./build.sh 
  - travis_wait 40 ./${TRAVIS_OS_NAME}-deploy.sh
